language: node_js
node_js:
  - 0.6
notifications:
  webhooks: http://bjb.io:7076
  irc:
    - "irc.mozilla.org#badges"
  email:
    recipients:
      - openbadges+ci@mozilla.com
before_script:
  - cp lib/environments/local-dist.js lib/environments/local.js
script:
  - cat test.sql | mysql
